### ISSUE TITLE
Some references to the removed file ExprUnify.v persist

### ISSUE THREAD

**Issue by ale-f** [gmalecha/mirror-core#74]
As of commit 44e23fa17b12a5844483e6d26fee50ee0d90af97, `theories/Lambda/ExprUnify.v` doesn't exist any more&mdash;but these files still depend on it:

* `examples/Cancel/CancelTac.v`
* `examples/Cancel/CancelTacNoMatch.v`
* `theories/Lambda/AutoSetoidRewriteRtac.v`

The `_CoqProject` file also contains a stray reference to `ExprUnify.v`.

**Comment by gmalecha** [comment]
Fixed in e47a6ba

**Comment by gmalecha** [comment]
Thanks.
